package ToDo::Model::ToDoDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ToDo::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:dbname=data/todo.db',
        user => '',
        password => '',
        todouser => q{},
        todopass => q{},
        AutoCommit => q{1},
    }
);

=head1 NAME

ToDo::Model::ToDoDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ToDo>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ToDo::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

SotaNakamori

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
