task/add:
  title:
    - rule: NOT_BLANK
      message: title is empty
    - rule: LENGTH
      message: title length less than 40
  description:
    - rule: LENGTH
      message: description length less than 1000
